version: '2'

services:

    cnn4strabismus:
        build: .
        command: >
            gunicorn -b 0.0.0.0:8084
              --certfile cert.pem
              --keyfile key.pem
              --access-logfile -
              --reload
              "CNN4Strabismus.app:create_app()"
        environment:
            PYTHONUNBUFFERED: 'true'
        volumes:
          - '.:/CNN4Strabismus'
        ports:
          - '8084:8084'
