version: '2'

services:

    cnn-4-strabismus:
        build: .
        command: >
            gunicorn -b 0.0.0.0:8000
              --access-logfile -
              --reload
              "CNN4Strabismus.app:create_app()"
        environment:
            PYTHONUNBUFFERED: 'true'
        volumes:
          - '.:/CNN4Strabismus'
        ports:
          - '8000:8000'
