name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --extension-pkg-whitelist=cv2 `find strabismus/detector -name \*.py -print`
        pylint --extension-pkg-whitelist=cv2 `find strabismus/unittests -name \*.py -print`
